name: Test and Build

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: |
         npm run test

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/dev'

    steps:
    - name: Install dependencies
      run: npm install
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: |
        npm run build
